apiVersion: v1
kind: Service
metadata:
  name: "{{ include "grader.name" . }}"
  labels:
    app.kubernetes.io/name: "{{ include "grader.fullname" . }}-app"
    app.kubernetes.io/instance: "{{ include "grader.name" . }}"
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "{{ include "grader.fullname" . }}-app"
    app.kubernetes.io/instance: "{{ include "grader.name" . }}"
  ports:
    - port: {{ .Values.port }}
      name: http
      protocol: TCP
      targetPort: http
