apiVersion: v2
name: grader
description: Helm chart for a data grading app
version: 0.1.0
appVersion: 1.0

dependencies:
  - name: mariadb
    version: 12.2.5
    repository: https://charts.bitnami.com/bitnami
